name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Utilisation de Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Set up database
      run: |
        # Django utilise SQLite par défaut donc pas besoin de configuration supplémentaire

    - name: Run tests
      run: |
        pipenv run python manage.py migrate
        pipenv run python manage.py test
      working-directory: ./softdesk
